version: "3.8"
services:
  app:
    build: ./
    image: winnable:latest
    volumes:
      - ./:/app/
    # Dont need if communication is container to host
    # ports: 
    #   - 2999:2999
    command: ["tail", "-f", "/dev/null"]
